# fly.toml app configuration file generated for fullstack-3-nniziw on 2024-12-21T17:28:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-4'
primary_region = 'arn'

[build]

[http_service]
internal_port = 3003
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 256
